tap "aws/tap"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "ansible"
brew "node"
brew "aws-cdk"
brew "awscli"
brew "bat"
brew "broot"
brew "cask"
brew "cfn-lint"
brew "cowsay"
brew "git"
brew "git-secrets"
brew "go"
brew "htop"
brew "jq"
brew "mas"
brew "nghttp2"
brew "nmap"
brew "packer"
brew "python@3.8"
brew "ranger"
brew "serverless"
brew "terraform"
brew "tldr"
brew "tmux"
brew "trash"
brew "tree"
brew "youtube-dl"
brew "aws/tap/aws-sam-cli"
cask "amazon-chime"
cask "anydesk"
cask "appcleaner"
cask "balenaetcher"
cask "brave-browser"
cask "cyberduck"
cask "dash"
cask "dashlane"
cask "discord"
cask "docker"
cask "fliqlo"
cask "github"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "maccy"
cask "microsoft-teams"
cask "notion"
cask "numi"
cask "postman"
cask "powershell"
cask "propresenter"
cask "slack"
cask "spotify"
cask "tableplus"
cask "teamviewer"
cask "the-unarchiver"
cask "tigervnc-viewer"
cask "visual-studio-code"
cask "whatsapp"
cask "xmind"
cask "zoom"
cask "logitech-camera-settings"
cask "propresenter"
cask "raspberry-pi-imager"
cask "remnote"
cask "tastyworks"
mas "Microsoft Remote Desktop", id: 1295203466
mas "Microsoft OneNote", id: 784801555
mas "Rakuten Cash Back", id: 1451893560
mas "Be Focused", id: 973134470
mas "Deliveries", id: 290986013
mas "GoodNotes", id: 1444383602
mas "Magnet", id: 441258766
mas "OneTab", id: 1540160809
mas "Spark", id: 1176895641
# cask "wireshark"
# cask "figma"
# cask "anki"
# cask "macmediakeyforwarder"
# cask "webex"